name = "onepipe"
main = "src/worker.ts"
compatibility_date = "2025-06-20"

# # KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
  binding = "TOKEN_CACHE"
  id = "ff34d1109f1340a9bed0fd859a42b45b"
  preview_id = "ff34d1109f1340a9bed0fd859a42b45b"

# # Durable Object binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects]]
# binding = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# # Bucket binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv#bucket
# [[buckets]]
# binding = "MY_BUCKET"
# name = "my-bucket"
# bucket_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# # Service binding - For more information: https://developers.cloudflare.com/workers/platform/services
# [[routes]]
# binding = "MY_SERVICE"
# pattern = "/api/*"
# script = "api.js"

# # Queue binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/queues
[[queues.producers]]
queue = "onepipe-queue"
binding = "QUEUE"

[[queues.consumers]]
 queue = "onepipe-queue"
 max_batch_size = 10 # optional: defaults to 10
 max_batch_timeout = 5 # optional: defaults to 5 seconds

[observability.logs]
enabled = true

# Environment Variables
# Non-sensitive variables can be set in [vars] sections
# Sensitive secrets should use: wrangler secret put SECRET_NAME

[vars]
# BigQuery configuration (non-sensitive)
# Override these in environment-specific sections below
BIGQUERY_PROJECT_ID = ""
BIGQUERY_DATASET_ID = ""

[env.staging]
name = "onepipe-staging"
[env.staging.vars]
BIGQUERY_PROJECT_ID = ""
BIGQUERY_DATASET_ID = ""

[env.production]  
name = "onepipe-production"
[env.production.vars]
BIGQUERY_PROJECT_ID = ""
BIGQUERY_DATASET_ID = ""

# Secrets (set via wrangler CLI):
# wrangler secret put GOOGLE_CLOUD_CREDENTIALS
# wrangler secret put GOOGLE_CLOUD_CREDENTIALS --env staging  
# wrangler secret put GOOGLE_CLOUD_CREDENTIALS --env production

